server:
  port: 8088
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_c8f98d60710e
    token: wxtoken
    app-id: wx2bfae64099dbf070
    app-secret: b2dba393e3e87077d5746cc01bdf9163
    template_id: 4YJNL1e8ff1mBNeMbHwFS-AtkomZW3MBe6pqRiwQxrM


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml


# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000143681725
#  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfA35JOtwq5K6qcF/XwLOnh5881qzYPnRTpxteOmPpHJ+NSC7p1I01TJU9l4kFpdoOuYZ36a5zZkvMAm7SGkT7a4vB+CFegcAEXsZ32aJmxhc9dC5DY2NpnUHMr7FafmJwUrIWTMq0ysfxwBy0eOJ1CXS5j1hSKEBKUF/IM1Sp4s5RovTykCN2SEFUkBr7KgTGFrO2IAmlmDF+RlFTqn/wrrAxhb1n9lVXFpuGdQWiQ44QCadc36euY+S8ou4LYfQEHRIMlGRyeZ8QxPlW1LrdmeFeHdXMCOUlqupf4qMJf0BwBkOBcfUytId1bu8knAC8dnuw73Pv2wHxrlgSOpHzAgMBAAECggEAEB43h866kHJ7rfUUEfeLfljF8FHGVWkHO499u7BpfjCTj6uYbcVIxvVLT2Hz1qm4D7QIiFEciL/+wOAiQZO+GEoPcYroPv8h6o98yJs71fUQV/9VzSje486347qPXJ/g9Ie9W3tPNMI1QDD79+Mk+T4LIeAA0NsZoS7CdrWVSF721tnIjQ7kFgBX9wyt/4iSBGQwjQVO+R8pslBlnHRGVgqjzTVyPAmFJqIcGff1So+AraxJWLdHuDbD2j7lmvhhKp1K6YNw6PeN60JYBiT6DZ6wToKnlIPaMEfqmD5d2pklwuj7UX5RS6ysmVZf5o0GNA9MnLUG7XvCBVH+A9zGIQKBgQDkzNsHOly2bKXFsj0760OH6Y0ojcL2t0gcX3ckMHlGv49UcY/RiZWQhnXcIhpwZHd440desmeEyV/HQS+L+U7kyhkx5Kd/ll51Ce+S/ug488kOXw7SSAMzcr7dhhkeXXWvPvZtnoGDpNH8pMrNJgPBo3K7mSTx7gOK2Zec7TlnsQKBgQCx6s1sgwDIc3qPY2gkTfYS7N5xQLloiwlpupJKghziUVcWsp4KVShrtkI6IPNfE8LwtlYv9rWfz9c3nBneKguAQVukZJGVfy0MtRY/Dj3QASPzb8fBdQPHWfmetNT1vYh0esEOtb/lNBhn+i9RjULIBAgAhrbApftmjw0pNhWg4wKBgQDVBSnTs/HH4qYAx28dj3ADZV4IaNwhSgl4aSWK6xqu1QEEVOra4ub+dUHcX2AQTmmxgqHbN+0Lg1WKNVWoU8ixWLxWaJXOQ1jUTRjh2jSpecgyeixZebSJPQcZRpWyYL+GFu/mpZHd2CGtwFwU3pTWv2+929q66KghqW7wKymsMQKBgDmDHk6CdoFVmvu49ZQuw2nQugNAGe8qaquLzPha4P1jr9Q9fwr2Bi/zZasmtaU5XR20w12T0ZhMdlSamF4Rl1ApUHdurwT1bFmcPAm8D80qYTWzH45wxfzuH9vmtqSNVQvaFogrxlFQKseJvzwMftbrPq703SSfQwofGfEFc65jAoGAEqHBa8SOgsOdkZEt33y3wclNdQu2X3DbHAmTXLrnE4VMO7YVTc0PqAcOxkKCyLGEBUSVDOc7fHPrRwQ1PvHeICX3BDIRtS1UNt9naP0DYV5nGqFFdHQVqEj41ouuQYcFYLh0R0SktrtT1MfdawjIcvqijJNOKqUWfP5G09HzDdc=
#  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkYuB6bG4vqAkNzUKa1aMVwKktE/9/+G86bDCfR4DhF16DEXY/QDCXMbJPoPk8XU2T1mUwprIU1cev228DiktP+nsxcKrAb2jO4lCPbnKgCmSRCyREn5Yi5a/togpQ8E/3oM0FiWR+ieDF/5urDBu948BBjhZp1MxMPr6QiumHaT+x2zWScCumAad4WbK+Hi69ppxq1FEiJ/9dybPk9i16AGqUdeCbrslgJhUyty/54AIuB+Bnxzk1NMZOIJwd8VmgVr/hu9eE1yNsuDgL2L5wypZ87jxPqSRiAxEEJ1sZYzw0JvGQJ9Ll0JT1LQRVHqihC3JSEjhGymoUTZ/37Ac1QIDAQAB
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfA35JOtwq5K6qcF/XwLOnh5881qzYPnRTpxteOmPpHJ+NSC7p1I01TJU9l4kFpdoOuYZ36a5zZkvMAm7SGkT7a4vB+CFegcAEXsZ32aJmxhc9dC5DY2NpnUHMr7FafmJwUrIWTMq0ysfxwBy0eOJ1CXS5j1hSKEBKUF/IM1Sp4s5RovTykCN2SEFUkBr7KgTGFrO2IAmlmDF+RlFTqn/wrrAxhb1n9lVXFpuGdQWiQ44QCadc36euY+S8ou4LYfQEHRIMlGRyeZ8QxPlW1LrdmeFeHdXMCOUlqupf4qMJf0BwBkOBcfUytId1bu8knAC8dnuw73Pv2wHxrlgSOpHzAgMBAAECggEAEB43h866kHJ7rfUUEfeLfljF8FHGVWkHO499u7BpfjCTj6uYbcVIxvVLT2Hz1qm4D7QIiFEciL/+wOAiQZO+GEoPcYroPv8h6o98yJs71fUQV/9VzSje486347qPXJ/g9Ie9W3tPNMI1QDD79+Mk+T4LIeAA0NsZoS7CdrWVSF721tnIjQ7kFgBX9wyt/4iSBGQwjQVO+R8pslBlnHRGVgqjzTVyPAmFJqIcGff1So+AraxJWLdHuDbD2j7lmvhhKp1K6YNw6PeN60JYBiT6DZ6wToKnlIPaMEfqmD5d2pklwuj7UX5RS6ysmVZf5o0GNA9MnLUG7XvCBVH+A9zGIQKBgQDkzNsHOly2bKXFsj0760OH6Y0ojcL2t0gcX3ckMHlGv49UcY/RiZWQhnXcIhpwZHd440desmeEyV/HQS+L+U7kyhkx5Kd/ll51Ce+S/ug488kOXw7SSAMzcr7dhhkeXXWvPvZtnoGDpNH8pMrNJgPBo3K7mSTx7gOK2Zec7TlnsQKBgQCx6s1sgwDIc3qPY2gkTfYS7N5xQLloiwlpupJKghziUVcWsp4KVShrtkI6IPNfE8LwtlYv9rWfz9c3nBneKguAQVukZJGVfy0MtRY/Dj3QASPzb8fBdQPHWfmetNT1vYh0esEOtb/lNBhn+i9RjULIBAgAhrbApftmjw0pNhWg4wKBgQDVBSnTs/HH4qYAx28dj3ADZV4IaNwhSgl4aSWK6xqu1QEEVOra4ub+dUHcX2AQTmmxgqHbN+0Lg1WKNVWoU8ixWLxWaJXOQ1jUTRjh2jSpecgyeixZebSJPQcZRpWyYL+GFu/mpZHd2CGtwFwU3pTWv2+929q66KghqW7wKymsMQKBgDmDHk6CdoFVmvu49ZQuw2nQugNAGe8qaquLzPha4P1jr9Q9fwr2Bi/zZasmtaU5XR20w12T0ZhMdlSamF4Rl1ApUHdurwT1bFmcPAm8D80qYTWzH45wxfzuH9vmtqSNVQvaFogrxlFQKseJvzwMftbrPq703SSfQwofGfEFc65jAoGAEqHBa8SOgsOdkZEt33y3wclNdQu2X3DbHAmTXLrnE4VMO7YVTc0PqAcOxkKCyLGEBUSVDOc7fHPrRwQ1PvHeICX3BDIRtS1UNt9naP0DYV5nGqFFdHQVqEj41ouuQYcFYLh0R0SktrtT1MfdawjIcvqijJNOKqUWfP5G09HzDdc=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkYuB6bG4vqAkNzUKa1aMVwKktE/9/+G86bDCfR4DhF16DEXY/QDCXMbJPoPk8XU2T1mUwprIU1cev228DiktP+nsxcKrAb2jO4lCPbnKgCmSRCyREn5Yi5a/togpQ8E/3oM0FiWR+ieDF/5urDBu948BBjhZp1MxMPr6QiumHaT+x2zWScCumAad4WbK+Hi69ppxq1FEiJ/9dybPk9i16AGqUdeCbrslgJhUyty/54AIuB+Bnxzk1NMZOIJwd8VmgVr/hu9eE1yNsuDgL2L5wypZ87jxPqSRiAxEEJ1sZYzw0JvGQJ9Ll0JT1LQRVHqihC3JSEjhGymoUTZ/37Ac1QIDAQAB
  notify_url: http://selenamafei.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
